#!/bin/bash
FUZZY_FINDER_CMD="fzy --lines=40"
if [[ $# -eq 1 ]]; then
    selected=$1
else
    if [[ -f /tmp/items ]]; then
        items=$(cat /tmp/items)
    else
        items=$(fd --type d --hidden '.+.git$' $HOME/code)
        items2=$(fd --type d --hidden '^\.git$' $HOME/code)
        items2=$(dirname $items2)
        items=$(printf "$items $items2 $HOME/Notes $HOME/.config")
        echo $items > /tmp/items
    fi
    selected=$(echo $items | tr ' ' '\n' | $FUZZY_FINDER_CMD)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
